// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIWHeT9LZ7faI_RnT521nYVVApUXnT3Ls',
    appId: '1:837250442226:web:493b9a9d226ce598b7416b',
    messagingSenderId: '837250442226',
    projectId: 'taste-app-bce4c',
    authDomain: 'taste-app-bce4c.firebaseapp.com',
    storageBucket: 'taste-app-bce4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmVQ7KlUF2sMct_0cFATq9t1B_qse2oU',
    appId: '1:837250442226:android:8a23ace2a328351eb7416b',
    messagingSenderId: '837250442226',
    projectId: 'taste-app-bce4c',
    storageBucket: 'taste-app-bce4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFzR0XOS386f52NjtQLFr81G5CCVqGPmQ',
    appId: '1:837250442226:ios:4d917b2b5241067bb7416b',
    messagingSenderId: '837250442226',
    projectId: 'taste-app-bce4c',
    storageBucket: 'taste-app-bce4c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIWHeT9LZ7faI_RnT521nYVVApUXnT3Ls',
    appId: '1:837250442226:web:5cbff837bfe7a9b4b7416b',
    messagingSenderId: '837250442226',
    projectId: 'taste-app-bce4c',
    authDomain: 'taste-app-bce4c.firebaseapp.com',
    storageBucket: 'taste-app-bce4c.appspot.com',
  );
}
